namespace CodexUsageWidget.Services;

/// <summary>
/// Immutable Vision Glass tokens. They are applied only when appearance
/// changes; the visual system does not require a timer or a render loop.
/// </summary>
internal sealed record WidgetSkinVisuals(
    IReadOnlyDictionary<string, string> Colors,
    string[] PanelGradient,
    string[] CollapsedGradient,
    string BodyFontFamily,
    string DisplayFontFamily,
    double CollapsedCornerRadius,
    double CapsuleCornerRadius,
    double PanelCornerRadius,
    double OverlayCornerRadius,
    double ToolTipCornerRadius,
    double ArchiveBadgeCornerRadius,
    double IconButtonCornerRadius,
    double TrendButtonCornerRadius,
    double CollapsedShadowBlur,
    double CollapsedShadowDepth,
    double CollapsedShadowOpacity,
    double CapsuleShadowBlur,
    double CapsuleShadowDepth,
    double CapsuleShadowOpacity,
    double PanelShadowBlur,
    double PanelShadowDepth,
    double PanelShadowOpacity,
    double OverlayShadowBlur,
    double OverlayShadowDepth,
    double OverlayShadowOpacity,
    string ShadowColor,
    double TabIndicatorWidth,
    double TabIndicatorHeight,
    double TabIndicatorCornerRadius,
    double TabSelectionCornerRadius,
    double RankingRowHeight,
    double RankingBarHeight,
    double RingStrokeThickness,
    double HeroFontSize,
    double SummaryValueFontSize,
    double ContentInset)
{
    public static WidgetSkinVisuals Create(bool useLightTheme) =>
        useLightTheme
            ? CreateLight()
            : CreateDark();

    private static WidgetSkinVisuals CreateLight() =>
        CreateCore(
            colors: Palette(
                primary: "#E9272B28",
                secondary: "#CA4E524F",
                muted: "#B05B605C",
                divider: "#38FFFFFF",
                accent: "#FF20A66C",
                good: "#FF20A66C",
                panel: "#54FFFFFF",
                iconHover: "#32FFFFFF",
                iconPressed: "#4AFFFFFF",
                toolTipBackground: "#EAF6FAF7",
                toolTipBorder: "#72FFFFFF",
                ringTrack: "#64FFFFFF",
                archiveBadge: "#48FFFFFF",
                barTrack: "#4AFFFFFF",
                lineFill: "#A8788A82",
                summaryBackground: "#0FFFFFFF",
                summaryBorder: "#32FFFFFF",
                summaryDivider: "#50FFFFFF",
                overlayScrim: "#561A1E1B",
                overlayBackground: "#DCF6F2EB",
                quotaBarTrack: "#56FFFFFF",
                capsulePrimary: "#FF202522",
                capsuleSecondary: "#FF3D4541",
                capsuleMuted: "#E34B534F",
                capsuleAccent: "#FF087A4B",
                capsuleGood: "#FF087A4B",
                capsuleWarning: "#FF9A5200",
                capsuleUrgent: "#FFA33A00",
                capsuleCritical: "#FFB4233B"),
            panelGradient:
            [
                "#E4FFFDF9",
                "#DEF6F1EA",
                "#E2E2DDD6",
            ],
            collapsedGradient:
            [
                "#C8FFFDF9",
                "#C0F7F1E9",
                "#C4E4DDD4",
            ],
            shadowColor: "#780F1713",
            collapsedShadowOpacity: 0.22,
            panelShadowOpacity: 0.24,
            overlayShadowOpacity: 0.28);

    private static WidgetSkinVisuals CreateDark() =>
        CreateCore(
            colors: Palette(
                primary: "#F5F2F7F4",
                secondary: "#D6C8D3CE",
                muted: "#B8AEB9B3",
                divider: "#2EFFFFFF",
                accent: "#FF65DEAA",
                good: "#FF65DEAA",
                panel: "#4218211E",
                iconHover: "#2EFFFFFF",
                iconPressed: "#46FFFFFF",
                toolTipBackground: "#E8141F1B",
                toolTipBorder: "#58FFFFFF",
                ringTrack: "#40FFFFFF",
                archiveBadge: "#2FFFFFFF",
                barTrack: "#30FFFFFF",
                lineFill: "#CBEAF6F0",
                summaryBackground: "#0AFFFFFF",
                summaryBorder: "#28FFFFFF",
                summaryDivider: "#30FFFFFF",
                overlayScrim: "#82060907",
                overlayBackground: "#D8101715",
                quotaBarTrack: "#3AFFFFFF",
                capsulePrimary: "#FFF5F7F6",
                capsuleSecondary: "#F2D5DDD9",
                capsuleMuted: "#D6B8C2BD",
                capsuleAccent: "#FF6BE0AD",
                capsuleGood: "#FF6BE0AD",
                capsuleWarning: "#FFFFCD72",
                capsuleUrgent: "#FFFFA052",
                capsuleCritical: "#FFFF737B"),
            panelGradient:
            [
                "#E2282F2D",
                "#DC161918",
                "#E0111211",
            ],
            collapsedGradient:
            [
                "#D0303936",
                "#C81B211F",
                "#CC121715",
            ],
            shadowColor: "#B0000000",
            collapsedShadowOpacity: 0.24,
            panelShadowOpacity: 0.28,
            overlayShadowOpacity: 0.34);

    private static WidgetSkinVisuals CreateCore(
        IReadOnlyDictionary<string, string> colors,
        string[] panelGradient,
        string[] collapsedGradient,
        string shadowColor,
        double collapsedShadowOpacity,
        double panelShadowOpacity,
        double overlayShadowOpacity) =>
        new(
            Colors: colors,
            PanelGradient: panelGradient,
            CollapsedGradient: collapsedGradient,
            BodyFontFamily: "Segoe UI Variable Text, Microsoft YaHei UI",
            DisplayFontFamily: "Segoe UI Variable Display, Microsoft YaHei UI",
            CollapsedCornerRadius: 35,
            CapsuleCornerRadius: 32,
            PanelCornerRadius: 30,
            OverlayCornerRadius: 22,
            ToolTipCornerRadius: 12,
            ArchiveBadgeCornerRadius: 5,
            IconButtonCornerRadius: 14,
            TrendButtonCornerRadius: 10,
            CollapsedShadowBlur: 22,
            CollapsedShadowDepth: 4,
            CollapsedShadowOpacity: collapsedShadowOpacity,
            CapsuleShadowBlur: 20,
            CapsuleShadowDepth: 3,
            CapsuleShadowOpacity: 0.22,
            PanelShadowBlur: 28,
            PanelShadowDepth: 8,
            PanelShadowOpacity: panelShadowOpacity,
            OverlayShadowBlur: 24,
            OverlayShadowDepth: 8,
            OverlayShadowOpacity: overlayShadowOpacity,
            ShadowColor: shadowColor,
            TabIndicatorWidth: 18,
            TabIndicatorHeight: 2,
            TabIndicatorCornerRadius: 1,
            TabSelectionCornerRadius: 10,
            RankingRowHeight: 25,
            RankingBarHeight: 1.8,
            RingStrokeThickness: 2.2,
            HeroFontSize: 58,
            SummaryValueFontSize: 17,
            ContentInset: 20);

    private static Dictionary<string, string> Palette(
        string primary,
        string secondary,
        string muted,
        string divider,
        string accent,
        string good,
        string panel,
        string iconHover,
        string iconPressed,
        string toolTipBackground,
        string toolTipBorder,
        string ringTrack,
        string archiveBadge,
        string barTrack,
        string lineFill,
        string summaryBackground,
        string summaryBorder,
        string summaryDivider,
        string overlayScrim,
        string overlayBackground,
        string quotaBarTrack,
        string capsulePrimary,
        string capsuleSecondary,
        string capsuleMuted,
        string capsuleAccent,
        string capsuleGood,
        string capsuleWarning,
        string capsuleUrgent,
        string capsuleCritical) =>
        new Dictionary<string, string>
        {
            ["PrimaryTextBrush"] = primary,
            ["SecondaryTextBrush"] = secondary,
            ["MutedTextBrush"] = muted,
            ["DividerBrush"] = divider,
            ["AccentBrush"] = accent,
            ["GoodBrush"] = good,
            ["PanelBrush"] = panel,
            ["IconHoverBrush"] = iconHover,
            ["IconPressedBrush"] = iconPressed,
            ["TabHoverBrush"] = "#00FFFFFF",
            ["TabSelectionBackgroundBrush"] = "#00FFFFFF",
            ["ToolTipBackgroundBrush"] = toolTipBackground,
            ["ToolTipBorderBrush"] = toolTipBorder,
            ["CollapsedBorderBrush"] = "#00FFFFFF",
            ["RingTrackBrush"] = ringTrack,
            ["ExpandedBorderBrush"] = "#00FFFFFF",
            ["HeaderBrush"] = "#00FFFFFF",
            ["ArchiveBadgeBrush"] = archiveBadge,
            ["BarTrackBrush"] = barTrack,
            ["LineFillBrush"] = lineFill,
            ["SummaryBackgroundBrush"] = summaryBackground,
            ["SummaryBorderBrush"] = summaryBorder,
            ["SummaryDividerBrush"] = summaryDivider,
            ["OverlayScrimBrush"] = overlayScrim,
            ["OverlayBackgroundBrush"] = overlayBackground,
            ["OverlayBorderBrush"] = "#00FFFFFF",
            ["QuotaBarTrackBrush"] = quotaBarTrack,
            ["CapsulePrimaryTextBrush"] = capsulePrimary,
            ["CapsuleSecondaryTextBrush"] = capsuleSecondary,
            ["CapsuleMutedTextBrush"] = capsuleMuted,
            ["CapsuleAccentBrush"] = capsuleAccent,
            ["CapsuleGoodBrush"] = capsuleGood,
            ["CapsuleWarningBrush"] = capsuleWarning,
            ["CapsuleUrgentBrush"] = capsuleUrgent,
            ["CapsuleCriticalBrush"] = capsuleCritical,
        };
}
